global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hosting-service"
    static_configs:
      - targets: ["hosting-service:8010"]
    metrics_path: "/metrics"

  - job_name: "provisioning-service"
    static_configs:
      - targets: ["hosting-provisioner-service:7010"]
    metrics_path: "/metrics"

  - job_name: "resources-service"
    static_configs:
      - targets: ["hosting-resources-service:2010"]
    metrics_path: "/metrics"

  - job_name: "notification-service"
    static_configs:
      - targets: ["hosting-notification-service:1010"]
    metrics_path: "/metrics"
