global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hosting-service"
    static_configs:
      - targets: ["hosting-api:8080"]
    metrics_path: "/metrics"

  - job_name: "provisioning-service"
    static_configs:
      - targets: ["hosting-provisioner:7070"]
    metrics_path: "/metrics"
